// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: gateway-service-appfirst.proto

package gateway_service

import (
	context "context"
	appfirst_service "github.com/HardDie/grpc_gateway_example/appfirst/pkg/appfirst_service"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AppFirst_Hello_FullMethodName = "/gateway.AppFirst/Hello"
)

// AppFirstClient is the client API for AppFirst service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppFirstClient interface {
	Hello(ctx context.Context, in *appfirst_service.HelloRequest, opts ...grpc.CallOption) (*appfirst_service.HelloResponse, error)
}

type appFirstClient struct {
	cc grpc.ClientConnInterface
}

func NewAppFirstClient(cc grpc.ClientConnInterface) AppFirstClient {
	return &appFirstClient{cc}
}

func (c *appFirstClient) Hello(ctx context.Context, in *appfirst_service.HelloRequest, opts ...grpc.CallOption) (*appfirst_service.HelloResponse, error) {
	out := new(appfirst_service.HelloResponse)
	err := c.cc.Invoke(ctx, AppFirst_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppFirstServer is the server API for AppFirst service.
// All implementations must embed UnimplementedAppFirstServer
// for forward compatibility
type AppFirstServer interface {
	Hello(context.Context, *appfirst_service.HelloRequest) (*appfirst_service.HelloResponse, error)
	mustEmbedUnimplementedAppFirstServer()
}

// UnimplementedAppFirstServer must be embedded to have forward compatible implementations.
type UnimplementedAppFirstServer struct {
}

func (UnimplementedAppFirstServer) Hello(context.Context, *appfirst_service.HelloRequest) (*appfirst_service.HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedAppFirstServer) mustEmbedUnimplementedAppFirstServer() {}

// UnsafeAppFirstServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppFirstServer will
// result in compilation errors.
type UnsafeAppFirstServer interface {
	mustEmbedUnimplementedAppFirstServer()
}

func RegisterAppFirstServer(s grpc.ServiceRegistrar, srv AppFirstServer) {
	s.RegisterService(&AppFirst_ServiceDesc, srv)
}

func _AppFirst_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(appfirst_service.HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppFirstServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppFirst_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppFirstServer).Hello(ctx, req.(*appfirst_service.HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppFirst_ServiceDesc is the grpc.ServiceDesc for AppFirst service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppFirst_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.AppFirst",
	HandlerType: (*AppFirstServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _AppFirst_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway-service-appfirst.proto",
}
