// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: gateway-service-appsecond.proto

/*
Package gateway_service is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package gateway_service

import (
	"context"
	"io"
	"net/http"

	"github.com/HardDie/grpc_gateway_example/appsecond/pkg/appsecond_service"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_AppSecond_Hello_0(ctx context.Context, marshaler runtime.Marshaler, client AppSecondClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq appsecond_service.HelloRequest
	var metadata runtime.ServerMetadata

	msg, err := client.Hello(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_AppSecond_Hello_0(ctx context.Context, marshaler runtime.Marshaler, server AppSecondServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq appsecond_service.HelloRequest
	var metadata runtime.ServerMetadata

	msg, err := server.Hello(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterAppSecondHandlerServer registers the http handlers for service AppSecond to "mux".
// UnaryRPC     :call AppSecondServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterAppSecondHandlerFromEndpoint instead.
func RegisterAppSecondHandlerServer(ctx context.Context, mux *runtime.ServeMux, server AppSecondServer) error {

	mux.Handle("GET", pattern_AppSecond_Hello_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/gateway.AppSecond/Hello", runtime.WithHTTPPathPattern("/api/v1/second"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_AppSecond_Hello_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AppSecond_Hello_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterAppSecondHandlerFromEndpoint is same as RegisterAppSecondHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterAppSecondHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterAppSecondHandler(ctx, mux, conn)
}

// RegisterAppSecondHandler registers the http handlers for service AppSecond to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterAppSecondHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterAppSecondHandlerClient(ctx, mux, NewAppSecondClient(conn))
}

// RegisterAppSecondHandlerClient registers the http handlers for service AppSecond
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "AppSecondClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "AppSecondClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "AppSecondClient" to call the correct interceptors.
func RegisterAppSecondHandlerClient(ctx context.Context, mux *runtime.ServeMux, client AppSecondClient) error {

	mux.Handle("GET", pattern_AppSecond_Hello_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/gateway.AppSecond/Hello", runtime.WithHTTPPathPattern("/api/v1/second"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_AppSecond_Hello_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_AppSecond_Hello_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_AppSecond_Hello_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"api", "v1", "second"}, ""))
)

var (
	forward_AppSecond_Hello_0 = runtime.ForwardResponseMessage
)
